### ISSUE TITLE
DailyProvider does not cleanup the inner callObject state

### ISSUE THREAD

**Issue by dherault** [daily-co/daily-react-hooks#2]
# Expected behavior

`DailyProvider` should cleanup its own internal `callObject` state when going from `passed callObject` to `passed null`.

# Describe the bug (unexpected behavior)

I want my application behind `DailyProvider` to be able to know that the `callObject` has been destroyed. Currently when passing a `callObject` everything is fine, but when that `callObject` is set to `null` afterwards, `DailyProvider` still hold the previous reference.

# Steps to reproduce

1 - Pass a `callObject` to `DailyProvider` from a `setState` hook.
2 - Set that hook to null
3 - The previous `callObject` still remains inside of `DailyProvider`

# Screenshots

# System information 

 

* Device: MacBook Pro
* OS, version: lastest
* Browser, version: Chrome latest

# Additional context

 <3
I love your product.

**Comment by dherault** [comment]
That's a sweet curve if I know my curves.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/4154003/183424152-0c77d85f-45be-42bf-84da-b369821c19b5.png">

**Comment by Regaddi** [comment]
Thank you, @dherault, for the report!

I think you're right: when a passed `callObject` changes to `null` or `undefined`, we should let go the internal reference as well.

We'll look into this 🙇

**Comment by dherault** [comment]
Any news on this? I might use a fork soon.

**Comment by markbackman** [comment]
Hi @dherault, we've patched this issue and are planning to release it by the end of the week.

**Comment by dherault** [comment]
Was this included in 0.30.0? I don't see it in the release log.

**Comment by dherault** [comment]
Btw you made a typo in the release log. It's 30 not 3.

**Comment by prothweil** [comment]
We've released version [0.4.0](https://github.com/daily-co/daily-react-hooks/releases/tag/daily-react-hooks-2022-08-23-0.4.0) today, where the fix was included!
